---
listen_port: 5555
debug: true

mongo:
  uri: "mongodb://127.0.0.1:27017/?w=1"
  db_name: alhazerd
  media_collection: "medias"
  user_collection: "users"
  max_pool_size: 100
  wait_queue_multiple: 10
  wait_queue_timeout_ms: null

graphite:
  enable: false
  host: 127.0.0.1
  port: 2003

storage:
  thumbnails_path: ./data/thumbnails
  medias_path: ./data/medias